(in-package :regex-library)

(defun equal-elements-p (vec1 vec2)
  (and (= (length vec1) (length vec2))
       (loop for i from 0 below (length vec1)
             always (= (aref vec1 i) (aref vec2 i)))))

(deftest run-unicode-tests "unicode"
  (test-unicode-empty-ast-table #'assert-true) ;; Проверка, что все символы имеют одинаковый class-id для выражения "()"
  (test-unicode-disjoint-ranges-table #'assert-true) ;; Проверка того, что для выражения "[a-zA-Zа-яА-Я-]" будет создано 5 + 2 класса с соответствующими диапазонами
  (test-unicode-binary-search #'assert-true #'assert-equal) ;; Проверка того, что для символов из разных классов правильно находится class-id для выражения "[a-zA-Zа-яА-Я-]"
  (test-unicode-intersecting #'assert-true) ;; Проверка правильного создания классов и последующего определения class-id для пересекающихся диапазонов "[D-K]{3,4}[F-X]*"
)

;; Проверка, что все символы имеют одинаковый class-id для выражения "()"
(defun test-unicode-empty-ast-table (assert-true-fn)
  (let ((eq-table (make-equivalence-table-from-ast (parse-regex "()"))))
    (funcall assert-true-fn (= (equivalence-table-num-classes eq-table) 1)
     "Таблица для \"()\": создан ровно один класс")
    (funcall assert-true-fn (equal-elements-p (equivalence-table-endpoints eq-table) (vector 0 +right-class-bound+)) ;; FIXME: возможно нужно прописывать отдельную функцию сравнения элементов
     "Таблица для \"()\": Точки в массиве таблицы = (vector 0 +max-unicode+)")
  )
) 

(defun test-unicode-disjoint-ranges-table (assert-true-fn)
  "Проверка создания классов для выражения [a-zA-Zа-яА-Я-]"
  (let ((eq-table (make-equivalence-table-from-ast (parse-regex "[a-zA-Zа-яА-Я-]"))))
    (funcall assert-true-fn (= (equivalence-table-num-classes eq-table) 10)
     "Таблица для \"[a-zA-Zа-яА-Я-]\": создано 10 классов")
    (funcall assert-true-fn (= (aref (equivalence-table-endpoints eq-table) 0) 0)
     "Таблица для \"[a-zA-Zа-яА-Я-]\": первая точка = 0")
    (funcall assert-true-fn (= (aref (equivalence-table-endpoints eq-table) (1- (length (equivalence-table-endpoints eq-table)))) +right-class-bound+)
     "Таблица для \"[a-zA-Zа-яА-Я-]\": последняя точка = +right-class-bound+")
  )
)

(defun test-unicode-binary-search (assert-true-fn assert-equal-fn)
  "Проверка бинарного поиска class-id для выражения [a-zA-Zа-яА-Я-]"
  (let ((eq-table (make-equivalence-table-from-ast (parse-regex "[a-zA-Zа-яА-Я-]"))))
    ;; Проверяем, что разные символы из одного диапазона имеют одинаковый class-id
    (let ((class-lower-a (char-to-class-id #\a eq-table))
          (class-lower-g (char-to-class-id #\g eq-table))
          (class-lower-z (char-to-class-id #\z eq-table))
          (class-hyphen (char-to-class-id #\- eq-table))
          (class-upper-a (char-to-class-id #\A eq-table))
          (class-upper-z (char-to-class-id #\Z eq-table))
          (class-upper-d (char-to-class-id #\D eq-table))
          (class-upper-ru-a (char-to-class-id #\А eq-table))
          (class-upper-ru-ya (char-to-class-id #\Я eq-table))
          (class-greek-t (char-to-class-id (code-char 882) eq-table))
          )
      ;; (0-44) (1: 45-45 '-') (46-64) (3: 65-90 A-Z) (91-96) (5: 97-122 a-z) (123-1039) 
      ;; (7: 1040 - 1071 А-Я) (8: 1072-1103 а-я) (...)
      (funcall assert-true-fn (= class-lower-a class-lower-g class-lower-z 5)
       "Таблица для \"[a-zA-Zа-яА-Я-]\": 'a', 'g', 'z' имеют class-id = 5")
      (funcall assert-true-fn (= class-upper-a class-upper-d class-upper-z 3)
       "Таблица для \"[a-zA-Zа-яА-Я-]\": 'A', 'D', 'Z' имеют class-id = 3")
       (funcall assert-true-fn (= class-upper-ru-a class-upper-ru-ya 7)
       "Таблица для \"[a-zA-Zа-яА-Я-]\": 'А', 'Я' имеют class-id = 7")
       (funcall assert-true-fn (= class-hyphen 1)
       "Таблица для \"[a-zA-Zа-яА-Я-]\": '-' имеет class-id = 1")
       (funcall assert-true-fn (= class-greek-t 6)
       "Таблица для \"[a-zA-Zа-яА-Я-]\": 'Ͳ' имеет class-id = 6")
    )
  )
)

(defun test-unicode-intersecting (assert-true-fn)
  "Проверка создания классов для пересекающихся диапазонов [D-K]{3,4}[F-X]*"
  (let ((eq-table (make-equivalence-table-from-ast (parse-regex "[D-K]{3,4}[F-X]*"))))
    ;; [D-K] и [F-X] пересекаются на [F-k]
    ;; (0-67) (1: D-E) (2: F-K) (3: L-X) (4: ...)
    (funcall assert-true-fn (= (equivalence-table-num-classes eq-table) 5)
     "Таблица для \"[D-K]{3,4}[F-X]*\": создано 5 классов")
    (let ((class-lower-a (char-to-class-id #\a eq-table))
          (class-lower-g (char-to-class-id #\g eq-table))
          (class-lower-z (char-to-class-id #\z eq-table))
          (class-upper-d (char-to-class-id #\D eq-table))
          (class-upper-e (char-to-class-id #\E eq-table))
          (class-upper-f (char-to-class-id #\F eq-table))
          (class-upper-h (char-to-class-id #\H eq-table))
          (class-upper-j (char-to-class-id #\J eq-table))
          (class-upper-k (char-to-class-id #\K eq-table))
          (class-upper-l (char-to-class-id #\L eq-table))
          (class-upper-r (char-to-class-id #\R eq-table))
          (class-upper-x (char-to-class-id #\X eq-table))
          )
      (funcall assert-true-fn (= class-upper-d class-upper-e 1)
       "Таблица для \"[D-K]{3,4}[F-X]*\": 'D', 'E' имеют class-id = 1")
      (funcall assert-true-fn (= class-upper-f class-upper-h class-upper-j class-upper-k 2)
       "Таблица для \"[D-K]{3,4}[F-X]*\": 'F', 'H', 'J', 'K' имеют class-id = 2")
      (funcall assert-true-fn (= class-upper-l class-upper-r class-upper-x 3)
       "Таблица для \"[D-K]{3,4}[F-X]*\": 'L', 'R', 'X' имеют class-id = 3")
      (funcall assert-true-fn (= class-lower-a class-lower-g class-lower-z 4)
       "Таблица для \"[D-K]{3,4}[F-X]*\": 'a', 'g', 'z' имеют class-id = 4")
      (format t "~S ~S ~S~%" class-upper-k class-upper-r class-upper-x)
    )
  )
)