(in-package :regex-library)

(defun make-test-nfa (states-edges-list)
  (let ((vec (make-array (length states-edges-list) :element-type 'list)))
    (dotimes (i (length states-edges-list))
      (setf (aref vec i)
            (mapcar (lambda (e)
                      (make-nfa-edge :label (first e) :target (second e)))
                    (nth i states-edges-list))))
    (make-nfa :states vec :start-state 0 :accept-state (1- (length states-edges-list)))))

(defun make-test-buffers (nfa-size)
  (values (make-array (max 16 (* nfa-size 2)) :fill-pointer 0 :adjustable t)
          (make-array nfa-size :element-type 'bit :initial-element 0)))

(deftest run-nfa-closure-tests "nfa/closure"
  (test-closure-basic-traversal #'assert-true)
  (test-closure-cycles-and-dedup #'assert-true)
  (test-closure-individual-anchors #'assert-true)
  (test-closure-complex-graphs #'assert-true))

(defun test-closure-basic-traversal (assert-true-fn)
  (let ((nfa (make-test-nfa '(()))))
    (multiple-value-bind (q v) (make-test-buffers 1)
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) 0 :queue q :visited v) #(0))
               "одиночное состояние без переходов дает #(0)")))

  (let ((nfa (make-test-nfa '( ((:epsilon 1)) ((:epsilon 2)) ((:epsilon 3)) () ))))
    (multiple-value-bind (q v) (make-test-buffers 4)
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) 0 :queue q :visited v) #(0 1 2 3))
               "линейная цепочка эпсилон-переходов")))

  (let ((nfa (make-test-nfa '( ((:epsilon 1)) ((5 2)) ((:epsilon 3)) () ))))
    (multiple-value-bind (q v) (make-test-buffers 4)
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) 0 :queue q :visited v) #(0 1))
               "обход останавливается на символьном переходе (Class ID)")))

  (let ((nfa (make-test-nfa '( ((:epsilon 1) (:epsilon 2))
                               ((:epsilon 3)) ((:epsilon 4)) () () ))))
    (multiple-value-bind (q v) (make-test-buffers 5)
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) 0 :queue q :visited v) #(0 1 2 3 4))
               "разветвляющееся дерево эпсилон-переходов"))))

(defun test-closure-cycles-and-dedup (assert-true-fn)
  (let ((nfa (make-test-nfa '( ((:epsilon 0)) ))))
    (multiple-value-bind (q v) (make-test-buffers 1)
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) 0 :queue q :visited v) #(0))
               "петля на самом себе не вызывает зацикливания")))

  (let ((nfa (make-test-nfa '( ((:epsilon 1)) ((:epsilon 2)) ((:epsilon 0)) ))))
    (multiple-value-bind (q v) (make-test-buffers 3)
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) 0 :queue q :visited v) #(0 1 2))
               "взаимный цикл полностью обходится и завершается")))

  (let ((nfa (make-test-nfa '( ((:epsilon 1) (:epsilon 2))
                               ((:epsilon 3)) ((:epsilon 3)) () ))))
    (multiple-value-bind (q v) (make-test-buffers 4)
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) 0 :queue q :visited v) #(0 1 2 3))
               "несколько путей в один узел не создают дубликатов")))

  (let ((nfa (make-test-nfa '( ((:epsilon 1)) () ((:epsilon 3)) () ))))
    (multiple-value-bind (q v) (make-test-buffers 4)
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(2 0 0) 0 :queue q :visited v) #(0 1 2 3))
               "входное множество с дубликатами корректно обрабатывается"))))

(defun test-closure-individual-anchors (assert-true-fn)
  ;; Граф для позитивных якорей (без \B)
  (let ((nfa (make-test-nfa '( ((:anchor-start 1)
                                (:anchor-start-of-text 2)
                                (:anchor-end 3)
                                (:anchor-end-of-text-or-newline 4)
                                (:anchor-end-of-text 5)
                                (:anchor-word-boundary 6))
                               () () () () () () ))))
    (multiple-value-bind (q v) (make-test-buffers 7)
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) #b000001 :queue q :visited v) #(0 1))
               "якорь ^ активен при бите 0")
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) #b000010 :queue q :visited v) #(0 2))
               "якорь \\A активен при бите 1")
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) #b000100 :queue q :visited v) #(0 3))
               "якорь $ активен при бите 2")
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) #b001000 :queue q :visited v) #(0 4))
               "якорь \\Z активен при бите 3")
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) #b010000 :queue q :visited v) #(0 5))
               "якорь \\z активен при бите 4")
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) #b100000 :queue q :visited v) #(0 6))
               "якорь \\b активен при бите 5")))

  ;; Отдельный граф для проверки инвертированного якоря \B
  (let ((nfa-non-wb (make-test-nfa '( ((:anchor-non-word-boundary 1)) () ))))
    (multiple-value-bind (q v) (make-test-buffers 2)
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa-non-wb #(0) #b000000 :queue q :visited v) #(0 1))
               "якорь \\B активен при сброшенном 5-м бите")
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa-non-wb #(0) #b100000 :queue q :visited v) #(0))
               "якорь \\B заблокирован при установленном 5-м бите"))))

(defun test-closure-complex-graphs (assert-true-fn)
  (let ((nfa (make-test-nfa '( ((:anchor-start 1) (:anchor-end 4))
                               ((:epsilon 2))
                               ((:anchor-word-boundary 3))
                               ()
                               ((:epsilon 5))
                               () ))))
    (multiple-value-bind (q v) (make-test-buffers 6)
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) #b100001 :queue q :visited v) #(0 1 2 3))
               "комплекс: составной путь с несколькими якорями (^ и \\b)")
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) #b000100 :queue q :visited v) #(0 4 5))
               "комплекс: альтернативный путь по $")
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) #b000001 :queue q :visited v) #(0 1 2))
               "комплекс: частичный путь из-за невыполнения 2-го якоря")))

  (let ((nfa (make-test-nfa '( ((:epsilon 1))
                               ((:anchor-word-boundary 2))
                               ((:epsilon 0) (:epsilon 3))
                               () ))))
    (multiple-value-bind (q v) (make-test-buffers 4)
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) #b100000 :queue q :visited v) #(0 1 2 3))
               "комплекс: зацикленное пространство с условным якорем")
      (funcall assert-true-fn (equalp (compute-nfa-closure nfa #(0) 0 :queue q :visited v) #(0 1))
               "комплекс: блокировка зацикленного перехода при неактивном якоре"))))